# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.TextField(default='', unique=True)),
                ('is_host_blacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='URLMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(blank=True, max_length=10, null=True)),
                ('path', models.TextField(blank=True, default='')),
                ('is_url_blacklisted', models.BooleanField(default=False)),
                ('hash', models.CharField(db_index=True, max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_filter.Host')),
            ],
        ),
    ]
